FDio/site

README.md
Signed-off-by: John DeNisco <jadenisco@gmail.com>
=> Add setup to the README

config.toml, content/news/_index.md, content/news/bolsters-kubernetes.md, content/news/cisco-blogs.md, content/news/improve-kubernetes.md, content/news/lf-virtual-switch.md, content/news/light-reading-networks-on-demand.md, content/news/light-reading-verizon.md, content/news/packet-speeds-double.md, content/news/pq-show.md, content/news/telecom-tv.md, content/news/unmasking-fdio.md, layouts/events/list.html, layouts/news/list.html
Signed-off-by: John DeNisco <jadenisco@gmail.com>
=> First cut at news

.gitignore, README.md
This looks good. Thanks Ed. +1
=> Add guidnace on DNS records.

Makefile
=> Add Makefile to build docs from VPP repo

README.md
Signed-off-by: Ole Troan <ot@cisco.com>
=> Update README.md with me as new VPP represenative, replacing John.

content/latest/news/terabit_ipsec.md, content/latest/singles/terabit_ipsec.md, layouts/article/single.html, layouts/partials/article-header.html
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
=> Added News item for Terabit IPSEC

content/community/tscdocs/technical_community_doc.md
Revised to reflect https://docs.google.com/presentation/d/1kJ0uI3S6Ka5JdtFQh9XYwGq9fWRaQH4RHkzKf55TTgc/edit#slide=id.gca88b1a448_0_197
=> Revision of Technical Community Doc to reflect TSC Evolution

content/latest/webinars/2021_10_12_calico_vpp_low_trust_edge_network_no_problem.md, content/latest/webinars/2021_10_15_calico_vpp_using_calico_pluggable_dataplanes.md
=> webinars: calico/vpp add ppt links

content/latest/webinars/2021_10_12_calico_vpp_low_trust_edge_network_no_problem.md, content/latest/webinars/2021_10_15_calico_vpp_using_calico_pluggable_dataplanes.md
=> webinars: Add calico/vpp video links

content/getinvolved/tsc.md
Signed-off-by: Ole Troan <ot@cisco.com>
=> TSC: Fix Maciek profile formatting.

public/_redirects, static/vpp_versions.json
=> version: Add VPP release 22.02

content/latest/news/talk-to-applications-from-vpp.md, content/latest/news/using-hpc-instructions-for-networking.md, content/latest/news/vpp-fat-binary-support.md
Signed-off-by: Ray Kinsella <mdr@ashroe.eu>
=> News: Using HPC instructions to accelerate FD.io

public/_redirects, static/vpp_versions.json
=> version: Add VPP release 22.06

public/_redirects, static/vpp_versions.json
=> version: Add VPP release 22.10

content/latest/news/lfn_inreview_fdio_2022.md
Add the LFN Blog 'In Review: FD.io in 2022' to Latest->News page.
Signed-off-by: Dave Wallace <dwallacelf@gmail.com>
=> Latest News: add LFN Blog 'In Review: FD.io in 2022'

content/latest/webinars/2021_02_07_calico_vpp_all_you_can_eat_networking_bringing_kubernetes_goodness_to_your_hungriest_workloads.md, content/latest/webinars/2021_07_22_calico_vpp_kubernetes_networking_with_boosters.md
=> webinars: add missing calico-vpp webinar

.gitignore, layouts/partials/head.html, netlify.toml
=> Upgrade hugo to 0.104.0

config.toml, content/community/_index.md, content/documentation/govpp.md
- Update Community Page with GoVPP & HICN badges/links
- Add GoVPP to main page Documentation tab
=> Add GoVPP project references

content/documentation/csit.md
Links to s3-docs replaced by links to csit.fd.io
=> Update links to CSIT documentation

content/news/press/csit2306.md, content/news/press/csit2310.md, content/news/press/vpp2310.md
Add VPP Release 23.10 & CSIT 23.10 Report to News / Press
=> news: VPP Release 23.10 & CSIT 23.10 Report

content/news/press/lfn_inreview_fdio_2023.md
FD.io 2023 Year in review report included in LF Networking 2023 Annual Report
=> Latest News: In Review, FD.io 2023

content/news/press/vpp-on-google-cloud.md, layouts/index.html
- update New Users VyOS link to latest blog post
- add News article about VPP on Google Cloud
=> FD.io web site updates

content/news/press/csit2406.md, content/news/press/intel_pantheon_stonework_scaleability.md, content/news/press/vpp-on-google-cloud.md, content/news/press/vpp-on-google-cloud2.md, content/news/press/vpp2402.md, content/news/press/vpp2406.md, layouts/index.html
- VPP & CSIT 24.06 Release
- Part 2 of VPP on Google Cloud article
- Intel solutions brief on Pantheon Tech StoneWorks
- Fix release notes URL in VPP 24.02 announcement
=> Latest FD.io News
